# -*- coding: utf-8 -*-
"""AI Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBjeFbbvteiqvXEtqklCmyECGaJKKrvu

**AI ASSIGNMENT 1**

1. Write a python Program to display the last digit of number(hint: Any number divide by 10 will return last digit)
"""

def last_digit(number):
    return number %10


number=int(input('Enter a number:'))
print('The last digit of the number is:',last_digit(number))

"""2. Write a function to Calculate Area and Perimeter of Rectangle"""

def Rectangle_Properties(Length, Width):
    area = Length * Width
    perimeter = 2 * (Length + Width)
    return area, perimeter

Length = float(input('Length value of a Rectangle: '))
Width = float(input('Width value of a Rectangle: '))

Area, Perimeter = Rectangle_Properties(Length, Width)

print("Area:", Area)
print("Perimeter:", Perimeter)

"""3. Write a python Program to find out given No is Prime or Not."""

def is_prime(number):
    if number <= 10:
        return False
    elif number <= 3:
        return True
    elif number % 2 == 0 or number % 3 == 0:
        return False
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    return True

# Test the function
num = int(input("Enter a number: "))
if is_prime(num):
    print(num, "is a prime number.")
else:
    print(num, "is not a prime number.")

"""4. Write a Python program that prompts the user to input three numbers and then determines and
prints the largest among them.
"""

# Prompt the user to input three numbers
num1 = float(input("num1:"))
num2 = float(input("num2:"))
num3 = float(input("num3:"))

# Determine the largest number
largest = num1
if num2 > largest:
    largest = num2
if num3 > largest:
    largest = num3

# Print the largest number
print("The largest number among", num1, ",", num2, ", and", num3, "is:", largest)

"""5. Write a Python program to calculate electricity bill (accept no of unit from user) according to following criteria: Unit Price
First 100 units  no charge
Next 100 units Rs 5 per Unit
After 200 Units Rs 10 per Unit
(For Example if input unit is 350 then total bill amount is 2000)
"""

def calculate_electricity_bill(units):
    if units <= 100:
        return 0
    elif units <= 200:
        bill = (units - 100) * 5
        return bill
    else:
        bill = (100 * 5) + ((units - 200) * 10)
        return bill

# Prompt the user to input the number of units
units = int(input("Enter the number of units consumed: "))

# Calculate the electricity bill
total_bill = calculate_electricity_bill(units)

# Print the total bill amount
print("Total bill amount is:", total_bill)

"""6. Write a program to accept numbers from 1-7 and display name of day like- 1 for sunday, 2 for Monday and so on."""

def day_name(num):
    days = {
        1: "Sun",
        2: "Mon",
        3: "Tues",
        4: "Wednes",
        5: "Thurs",
        6: "Fri",
        7: "Satur"
    }
    return days.get(number, "Invalid day")

# Prompt the user to input a number from 1 to 7
number = int(input("Enter a num from 1 to 7: "))

# Get the name of the day corresponding to the input number
day_name = day_name(number)

# Display the name of the day
print("The name of the day corresponding to", number, "is", day_name)

"""7. Write a python program to check given word is Palindrome or not"""

def is_palindrome(word):
    # Convert the word to lowercase
    word = word.lower()
    # Reverse the word
    reversed_word = word[::-1]
    # Check word is equal to its reverse
    if word == reversed_word:
        return True
    else:
        return False

word = input("Write a word: ")

if is_palindrome(word):
    print(word, "is a palindrome.")
else:
    print(word, "is not a palindrome.")

"""8. Download the Dataset- https://www.kaggle.com/datasets/mohamedafsal007/house-price-dataset-of-india
Load the dataset.
"""

import pandas as pd
import numpy as np

data = pd.read_csv('/content/drive/MyDrive/House Price India.csv.zip')
data

data.head()

from google.colab import drive
drive.mount('/content/drive')

"""9. Perform Univariate Analysis"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

variable = data['Price']
print(variable.describe())

mean_value = variable.mean()
median_value = variable.median()
standard_deviation = variable.std()

print("Mean: ", mean_value)
print("Median: ", median_value)
print("Standard Deviation: ",standard_deviation)

plt.hist(variable)
plt.xlabel('Values')
plt.ylabel('frequency')
plt.title('Distribution of Price')
plt.show()

plt.boxplot(variable)
plt.title('Box plot of Price')
plt.show()

"""**10**.**Perform** **Bivariate** **Analysis**"""

import seaborn as sns

sns.scatterplot(x='Price',y='living area',data=data)
plt.xlabel('Price')
plt.ylabel('Living area')
plt.title('Bivariate Ananlysis of Price vs Living Area')
plt.show()

data.head()

sns.boxplot(x='number of bedrooms', y='living area', data=data)
plt.xlabel('Number of bedrooms')
plt.ylabel('Living Area')
plt.title('Distribution of Living Area and Bedrooms')
plt.show()

correlation  = data['Price'].corr(data['Distance from the airport'])
print("Correlation coefficent:",correlation)

data.head()

"""11. Perform Descriptive Statistics"""

numerical_data = data.select_dtypes(include=[np.number])
print(numerical_data.describe())

location_counts = data['Postal Code'].value_counts()
print(location_counts)

